### ISSUE TITLE
[feat]: Enforce commit message linting so it always includes the github issue in the commit message

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#465]
This is usually done to maintain consistency, improve readability, and facilitate integration with other tools like issue trackers and release management systems.

Looks like there is a Github app to do this (preferred)

https://www.systango.com/blog/github-commit-messages-lint-reinforce-your-commits-with-git-hooks

Or if the app doesnt work we could try a commit message linting action

```
name: Commit Message Lint

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint Commit Messages
        run: |
          git log --format=%B ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | grep -qE '#[0-9]+'
        shell: bash

```
